Updating .dotfiles

diff --git a/scripts/zet b/scripts/zet
--- a/scripts/zet
+++ b/scripts/zet
@@ -1,4 +1,4 @@
-#!/bin/sh
+#/bin/sh
 set -e
 
 # This zet script is a multicall executable, which means you may have
@@ -11,8 +11,8 @@ set -e
 #
 # Note that you will need one such complete line for every multicall
 # variation of this script (ex: ln -s zet log; complete -C log log)
-
-test -z "$KN" && echo "KN (knowledge directory) not set." && exit 1
+ZETCONF="${ZETCONF:-$HOME/.config/zet/config.yml}"
+ZETDIR="${ZETDIR:-$HOME/.local/share}"
 test -z "$GITUSER" && echo "GITUSER not set." && exit 1
 
 EXE=${0##*/}
@@ -28,8 +28,8 @@ test -z "$EXE" && echo "Could not determine name of executable." && exit 1
 # for knowledge repos).
 
 add() {
-  test ! -d "$KN/$EXE" && echo "Directory not found: $KN/$EXE" && exit 1
-  dir="$KN/$EXE/$(isosec)"
+  test ! -d "$ZETDIR/$EXE" && echo "Directory not found: $ZETDIR/$EXE" && exit 1
+  dir="$ZETDIR/$EXE/$(isosec)"
   mkdir -p "$dir"
   ${EDITOR:-vim} "$dir/README.md"
   cd "$dir"
@@ -48,8 +48,7 @@ query() {
   term="$*"
   it="https://github.com/$GITUSER/$EXE/search?q=$(urlencode $term)"
   echo "[$term]: <$it>"
-  type wee >/dev/null 2>&1 || return 0
-  exec wee "$it"
+  exec "$it"
 }
 
 case "$1" in
